#此文件是使用在windows系统时的用法，linux系统该文件写法有点不同
version: '3'
services:
  #使用dokcerfile 编排
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./            # 指定设定上下文根目录，然后以该目录为准寻找Dockerfile
      dockerfile: ./src/main/docker/Dockerfile #DockerFile 真正所在位置
    restart: always          # 重启策略: 容器退出时总是重启容器
    ports:
      - 8761:8761            # 映射端口

  eureka-client:
    image: eureka-client
    container_name: eureka-client
    build:
      context: ./            # 指定设定上下文根目录，然后以该目录为准寻找Dockerfile
      dockerfile: ./src/main/docker/Dockerfile #DockerFile 真正所在位置
    restart: always
    ports:
      - 8763:8763