server:
  port: 8763

spring:
  application:
    name: consul-provider
  cloud:
    #consul注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: consul-provider
  profiles:
    active: dev
