server:
  port: 8762

spring:
  application:
    name: eureka-client
  sleuth:
    #设置web开启sleuth功能
    web:
      client:
        enabled: true
    #设置为1.0时就是链路数据100%收集到zipkin-server;设置为0.1时，即10%概率收集链路数据
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  #指定zipkin server的地址
  zipkin:
    #base-url: http://localhost:9411
    sender:
      type: rabbit
    #将链路数据存储在Mysql数据库中 mysql环境配置
    storage:
      type: mysql
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
